/*
 * @Author: your name
 * @Date: 2021-04-14 13:20:32
 * @LastEditTime: 2021-05-20 00:48:06
 * @LastEditors: Please set LastEditors
 * @Description: In User Settings Edit
 * @FilePath: /CMQ/include/message/cmq_message_global.h
 */

#ifndef CMQ_MESSAGE_GLOBAL_H
#define CMQ_MESSAGE_GLOBAL_H

namespace CMQ::Message{
//控制报文标志位，以下标志只出现在PUBLISH报文中，从MQTT3.1.1起被使用
#define MQTT_CONTROL_PACKET_FLAG_DUP 0x08    //重复分发标志位
#define MQTT_CONTROL_PACKET_FLAG_QOS_H 0x04  //PUBLISH报文服务质量标志高位
#define MQTT_CONTROL_PACKET_FLAG_QOS_L 0x02  //PUBLISH报文服务质量标志低位
#define MQTT_CONTROL_PACKET_FLAG_RETAIN 0x01 //PUBLISH报文的保留标志

//属性标志位
#define SESSION_EXPIRY_INTERVAL_IDENTIFIER 0X11
#define RECEIVE_MAXIMUM_IDENTIFIER 0X21
#define MAXIMUM_PACKET_SIZE_IDENTIFIER 0X27
#define TOPIC_ALIAS_MAXIMUM_IDENTIFIER 0X22
#define REQUEST_RESPONSE_INFO_IDENTIFIER 0X19
#define REQUEST_PROBLEM_INFO_IDENTIFIER 0X17
#define USER_PROPERTY_IDENTIFIER 0X26
#define AUTHENTICATION_METHOD_IDENTIFIER 0X15
#define AUTHENTICATION_DATA_IDENTIFIER 0X16
#define WILL_DELAY_INTERVAL_IDENTIFIER 0X18
#define PAYLOAD_FORMAT_INDICATOR_IDENTIFIER 0X01
#define MESSAGE_EXPIRY_INTERVAL_IDENTIFIER 0X02
#define CONTENT_TYPE_IDENTIFIER 0X03
#define RESPONSE_TOPIC_IDENTIFIER 0X08
#define CORRELATION_DATA_IDENTIFIER 0X09
#define MAXIMUM_QOS_IDENTIFIER 0X24
#define RETAIN_AVAILABLE_IDENTIFIER 0X25
#define ASSIGNED_CLIENT_IDENTIFIER 0X12
#define REASON_STRING_IDENTIFIER 0X1F
#define WILDCARD_SUBSCRIPTION_AVAILABLE_IDENTIFIER 0X28
#define SUBSCRIPTION_ID_AVAILABLE_IDENTIFIER 0X29
#define SERVER_KEEP_ALIVE_IDENTIFER 0X13
#define RESPONSE_INFORMATION_IDENTIFIER 0X1A
#define SERVER_REFERENCE_IDENTIFIER 0X1C
}

#endif